### ISSUE TITLE
getting jsondecode error

### ISSUE THREAD

**Issue by mnjagadeesh** [joelee2012/api4jenkins#103]
My code is:
from api4jenkins import Jenkins as aj
def api4jenkins_test(jenkins_url, username, password, job_name):
    client = aj(jenkins_url, auth=(username, password))
    item = client.build_job(job_name)
    while not item.get_build():
        time.sleep(1)
    build = item.get_build()
    for line in build.progressive_output():
        print(line)

Jenkins Version: Jenkins 2.346.1

Traceback (most recent call last):
  File "/home/njagadeesh/workspace/testjob/run_jenkins_api.py", line 52, in <module>
    api4jenkins_test(jenkins_url, username, password, job_name)
  File "/home/njagadeesh/workspace/testjob/run_jenkins_api.py", line 35, in api4jenkins_test
    item = client.build_job(job_name)
  File "/home/njagadeesh/ve3/lib/python3.10/site-packages/api4jenkins/__init__.py", line 185, in build_job
    job = self._get_job_and_check(full_name)
  File "/home/njagadeesh/ve3/lib/python3.10/site-packages/api4jenkins/__init__.py", line 189, in _get_job_and_check
    job = self.get_job(full_name)
  File "/home/njagadeesh/ve3/lib/python3.10/site-packages/api4jenkins/__init__.py", line 74, in get_job
    if folder.exists():
  File "/home/njagadeesh/ve3/lib/python3.10/site-packages/api4jenkins/item.py", line 111, in exists
    self.api_json(tree='_class')
  File "/home/njagadeesh/ve3/lib/python3.10/site-packages/api4jenkins/item.py", line 97, in api_json
    return self.handle_req('GET', 'api/json', params=params).json()
  File "/home/njagadeesh/ve3/lib/python3.10/site-packages/api4jenkins/item.py", line 100, in handle_req
    self._add_crumb(self.jenkins.crumb, kwargs)
  File "/home/njagadeesh/ve3/lib/python3.10/site-packages/api4jenkins/__init__.py", line 248, in crumb
    'GET', f'{self.url}crumbIssuer/api/json').json()
  File "/home/njagadeesh/ve3/lib/python3.10/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Not sure if this is older jenkins version

**Comment by joelee2012** [comment]
@mnjagadeesh are you able to access this url `<jenkins url>/crumbIssuer/api/json` in browser to check the return value

**Comment by mnjagadeesh** [comment]
Yes.
![image](https://github.com/joelee2012/api4jenkins/assets/4705969/0cf9c299-1145-452a-b2b0-74624944ce14)

**Comment by joelee2012** [comment]
@mnjagadeesh from your screenshot, the url for crumb return correct value.
can you run your code in a clean virtual env , and share how do you deploy the Jenkins?

**Comment by mnjagadeesh** [comment]
Jenkins is running on bare machine with Amazon corretto. I have used requests module. Shall we close it?
