### ISSUE TITLE
job.get_build() may throw an exception

### ISSUE THREAD

**Issue by dd-dino** [joelee2012/api4jenkins#107]
I have code that looks like this:
```
job = japi.build_job(job_name, **params)
while not job.get_build(): # this line throws exception
    time.sleep(1)
build = job.get_build()
```

and it occasionally throws an exception like this:
`Traceback (most recent call last):
. . .
in run_job
    while not job.get_build():
  File "/opt/scotty/bazel_install/execroot/__main__/bazel-out/k8-fastbuild/bin/middleware_v2/jenkins/replay_trend_branches.runfiles/dd_py_deps_api4jenkins/site-packages/api4jenkins/queue.py", line 55, in get_build
    self._build = self._new_item(
  File "/opt/scotty/bazel_install/execroot/__main__/bazel-out/k8-fastbuild/bin/middleware_v2/jenkins/replay_trend_branches.runfiles/dd_py_deps_api4jenkins/site-packages/api4jenkins/item.py", line 67, in _new_item
    return new_item(self.jenkins, module, item)
  File "/opt/scotty/bazel_install/execroot/__main__/bazel-out/k8-fastbuild/bin/middleware_v2/jenkins/replay_trend_branches.runfiles/dd_py_deps_api4jenkins/site-packages/api4jenkins/item.py", line 38, in func
    class_name = delimiter.split(item['_class'])[-1]
TypeError: 'NoneType' object is not subscriptable
`

**Comment by joelee2012** [comment]
@dd-dino it seems the queue item does not include executable object, is there any zombie queue item ?
