### ISSUE TITLE
misspelled in method plugins.set_site

### ISSUE THREAD

**Issue by Yotainming** [joelee2012/api4jenkins#22]
### error message
Traceback (most recent call last):
  File "jenkins_handler.py", line 52, in set_plugin_update_server
    self._jenkins.plugins.set_site(update_server)
  File "/usr/local/python375/lib/python3.7/site-packages/api4jenkins/plugin.py", line 38, in set_site
    self.check_update_server()
  File "/usr/local/python375/lib/python3.7/site-packages/api4jenkins/item.py", line 128, in __getattr__
    return super().__getattribute__(name)
AttributeError: 'PluginsManager' object has no attribute 'check_update_server'

### possible modification
plugin.py", line 38, in set_site
self.check_update_server() -> self.check_updates_server()

**Comment by joelee2012** [comment]
thanks for reporting issue.
yes, it was a typo, will fix it in next release. for now, here is workaround
```python
jenkins.plugins.handle_req('POST', 'siteConfigure', params={'site': url})
jenkins.plugins.check_updates_server()
```

**Comment by Yotainming** [comment]
@joelee2012 thanks a lot ~
